apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/jhutar-tenant/devfile-sample/devfile-sample@sha256:a6921c5d3a7e69bc16cdcba470b4c5e5070dd0f10ca2cb41544e59ff8d0b3408
        name: my-nodejs
        resources: {}
status: {}
